// <auto-generated />
namespace DKO.EQulay.Infra.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class criacaodb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacaodb));
        
        string IMigrationMetadata.Id
        {
            get { return "201411091546375_criacao db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
