// <auto-generated />
namespace DKO.EQulay.Infra.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ajustefkusuariocincoporque : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustefkusuariocincoporque));
        
        string IMigrationMetadata.Id
        {
            get { return "201411110135251_ajuste fk usuario cincoporque"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
