// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DKO.EQualy.Test.Specs.Specs.Servicos
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ServicoDeAlertaParaOUsuarioFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ServicoAlertaUsuario.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "ServicoDeAlertaParaOUsuario", "\r\nO sistema deve realizar alertas aos usuários", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "ServicoDeAlertaParaOUsuario")))
            {
                DKO.EQualy.Test.Specs.Specs.Servicos.ServicoDeAlertaParaOUsuarioFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("alertar o usuário que existem novas tarefas")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ServicoDeAlertaParaOUsuario")]
        public virtual void AlertarOUsuarioQueExistemNovasTarefas()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("alertar o usuário que existem novas tarefas", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Titulo",
                        "DataDeCriacao",
                        "DataDeConclusao",
                        "Tipo",
                        "Status",
                        "UsuarioDestinoId",
                        "Descricao"});
            table1.AddRow(new string[] {
                        "\"Nova tarefa\"",
                        "\"02/11/2014\"",
                        "\"10/11/2014\"",
                        "\"Elaboração de documento\"",
                        "\"Criada\"",
                        "1",
                        "\"O usuário XX solicita a criação do documento com código YY\""});
#line 13
testRunner.Given("as seguintes informações iniciais para a o envio de alerta do tipo tarefa", ((string)(null)), table1, "Dado ");
#line 17
testRunner.When("enviar o alerta de nova tarefa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 18
testRunner.Then("o serviço deve automaticamente registrar a nova tarefa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 19
testRunner.And("um email de notificação para a o usuario <UsuarioId> deve ser enviado com a segui" +
                    "nte mensagem \"Uma nova tarefa foi registrada para você.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void ListarAsTarefasPendentesParaOUsuario(string titulo, string tipo, string status, string dataConclusao, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar as tarefas pendentes para o usuario", exampleTags);
#line 23
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 24
testRunner.Given("o codigo do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 25
testRunner.When("executar a consulta das tarefas pertencentes ao usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Listar as tarefas pendentes para o usuario")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ServicoDeAlertaParaOUsuario")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\"Tarefa de teste\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Titulo", "\"Tarefa de teste\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Tipo", "\"Aprovação de documento\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Status", "\"Criada\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DataConclusao", "\"20/09/2014\"")]
        public virtual void ListarAsTarefasPendentesParaOUsuario_TarefaDeTeste()
        {
            this.ListarAsTarefasPendentesParaOUsuario("\"Tarefa de teste\"", "\"Aprovação de documento\"", "\"Criada\"", "\"20/09/2014\"", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
