// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DKO.EQualy.Test.Specs.Specs.Documentos
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ListarDocumentosFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ListarDocumentos.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "ListarDocumentos", "\r\nQuero consultar todos os documentos ja registrados e disponiveis em um determin" +
                    "ado peridodo", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "ListarDocumentos")))
            {
                DKO.EQualy.Test.Specs.Specs.Documentos.ListarDocumentosFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 10
#line hidden
        }
        
        public virtual void ListarDocumentosUtilizandoCombinacaoDeFiltrosSemRetornoDeDados(string titulo, string dataInicial, string dataFinal, string setorId, string fase, string status, string quantidadeDeRegistrosRetornados, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar Documentos utilizando combinação de filtros sem retorno de dados", exampleTags);
#line 13
this.ScenarioSetup(scenarioInfo);
#line 10
this.FeatureBackground();
#line 14
testRunner.Given(string.Format("os filtros por {0} e {1} e {2} e {3} e {4} e {5} para pesquisa sem registros", titulo, dataInicial, dataFinal, setorId, fase, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 15
testRunner.When("executar a consulta sem registros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 17
testRunner.Then("o número total de registros de documentos encontrados deve ser <QuantidadeTotalDe" +
                    "Registros>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Listar Documentos utilizando combinação de filtros sem retorno de dados")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListarDocumentos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\"Titulo\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Titulo", "\"Titulo\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DataInicial", "\"01/01/2000\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DataFinal", "\"31/12/2020\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SetorId", "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Fase", "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Status", "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:QuantidadeDeRegistrosRetornados", "0")]
        public virtual void ListarDocumentosUtilizandoCombinacaoDeFiltrosSemRetornoDeDados_Titulo()
        {
            this.ListarDocumentosUtilizandoCombinacaoDeFiltrosSemRetornoDeDados("\"Titulo\"", "\"01/01/2000\"", "\"31/12/2020\"", "1", "1", "1", "0", ((string[])(null)));
        }
        
        public virtual void ListarDocumentosUtilizandoCombinacaoDeFiltrosComRetornoDeDados(string titulo, string dataInicial, string dataFinal, string setorId, string fase, string status, string quantidadeTotalDeRegistrosComDados, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar Documentos utilizando combinação de filtros com retorno de dados", exampleTags);
#line 25
this.ScenarioSetup(scenarioInfo);
#line 10
this.FeatureBackground();
#line 26
testRunner.Given(string.Format("os filtros por {0} e {1} e {2} e {3} e {4} e {5} para pesquisa com registros", titulo, dataInicial, dataFinal, setorId, fase, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 27
testRunner.When("executar a consulta com registros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 29
testRunner.Then(string.Format("o número total de registros de documentos encontrados é  maior do que {0}", quantidadeTotalDeRegistrosComDados), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Listar Documentos utilizando combinação de filtros com retorno de dados")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListarDocumentos")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\"Titulo\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Titulo", "\"Titulo\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DataInicial", "\"01/01/2000\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DataFinal", "\"31/12/2020\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SetorId", "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Fase", "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Status", "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:QuantidadeTotalDeRegistrosComDados", "1")]
        public virtual void ListarDocumentosUtilizandoCombinacaoDeFiltrosComRetornoDeDados_Titulo()
        {
            this.ListarDocumentosUtilizandoCombinacaoDeFiltrosComRetornoDeDados("\"Titulo\"", "\"01/01/2000\"", "\"31/12/2020\"", "1", "1", "1", "1", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
